sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_3c4352e6fdc4_key -iv $encrypted_3c4352e6fdc4_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- |
  if [ ! -d $HOME/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
- BUILD_VERSION="1.3.5"
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file deploy-key.json
before_deploy:
- docker build --build-arg BOT_TOKEN=$BOT_TOKEN --build-arg BUILD_VERSION=$BUILD_VERSION --build-arg TYPEFORM_TOKEN=$TYPEFORM_TOKEN
  -t us.gcr.io/hawthorne-197812/hawthorne-bot:$BUILD_VERSION .
deploy:
  provider: script
  script: gcloud docker -- push us.gcr.io/hawthorne-197812/hawthorne-bot:${BUILD_VERSION}
  skip_cleanup: true
  on:
    branch: master
env:
- PATH=$PATH:$HOME/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
