sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_3c4352e6fdc4_key -iv $encrypted_3c4352e6fdc4_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- |
  if [ ! -d $HOME/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
- |
  if [ -v $TRAVIS_TAG ]; then
    TRAVIS_TAG="1.0-SNAPSHOT";
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file deploy-key.json
before_deploy:
- docker build --build-arg BOT_TOKEN=$BOT_TOKEN --build-arg TRAVIS_TAG=$TRAVIS_TAG
  -t us.gcr.io/hawthorne-197812/hawthorne-bot:$TRAVIS_TAG .
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
env:
- PATH=$PATH:$HOME/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
stages:
- name: deploy
  if: "(tag IS present AND env(TRAVIS_TAG) != 1.0-SNAPSHOT)"
