sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_3c4352e6fdc4_key -iv $encrypted_3c4352e6fdc4_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
- [ -z "$TRAVIS_TAG" ] && { TRAVIS_TAG="SNAPSHOT" }
- tar -xzf credentials.tar.gz
- mv client_secret.json src/main/resources/client_secret.json
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
- gcloud components install beta
before_deploy:
- docker build -t us.gcr.io/hawthorne-197812/hawthorne-bot:$TRAVIS_TAG .
deploy:
  provider: script
  script:
  - gcloud docker -- push us.gcr.io/hawthorne-197812/hawthorne-bot:$TRAVIS_TAG
  - gcloud beta compute instances update-container hawthorne-001 --container-image us.gcr.io/hawthorne-197812/hawthorne-bot:$TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
    branch: master
env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
  global:
    secure: SgjFEqGJgEAR8ORNR5+H/syS85/P/1xhcEMBhC74qV5sY1m0QkDtHpCb5MQNbuam6p28kse5ysjkSo4T8wkrg0Qpps1+u52FVCLXC4RxHR68iybN6vz7FWav3HbxQ5Ugo5oDKHtU5/5U7T6kcrTipH4SwRzrQYzbBPDyz36Amr4/RN0vO4CxyuuaVGTC5YVnECEVyDb8Qf7/hAbLe6yP/Rb4J9zLDzKzNP1hfGBaeLsHPfJPJhZ/bgXWX79EN8D2ZzxXIDXaiNsU7QJS1W1nPj902wo045pOOIzKcYOwKDqcUJJQm8TgyMeJf94aZtJL2cqUuNLMA/+gPbG4g3hiRRzONg9hwjEi3DygoLe3dQkIDL9uCI/DLf01riqlhLyXpRHXL32YERDaOMQOdBe/HeCu3v2Usdxz1oYfF+xdlT9mAV9TjrlhkpKXUm88WdxwMM3cB5t2sy0LLUwxzY8jYKaCKOdQd2znnBacRkKtQC5a/OQvKAohaTqC6XOnmP54IgbZeJrhU7mj0nL+o8lbxBU6cw+OTHGxaZtmaqT4Hqku0h8AosdcJMfeotwlytvRfZ1U9/UJmEoJBBW0fdJnl7LaX6wkVCSeYFiZJT0OzAMr/UeGI3Ar/lUmYLWJs1rLWpsUHPAmyo2S8Q6EgeXdg56hfbKvUprlwQ2l2/IltSY=
